# Generated by Django 5.0.1 on 2024-02-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
