# Generated by Django 5.0.1 on 2024-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfirmation',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='userconfirmation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
