# Generated by Django 5.0.1 on 2024-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_userconfirmation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='new_phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
