# Generated by Django 5.0.1 on 2024-02-26 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComforsTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('count_rooms', models.IntegerField(choices=[(1, '1 xona'), (2, '2 xona'), (3, '3 xona'), (4, '4 xona'), (5, '5 xona'), (6, '6 va undan ortiq xonalar'), (7, 'Studiya'), (8, 'Ochiq plan')], default=1)),
                ('vip', models.BooleanField(default=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('building_floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repair', models.CharField(choices=[('Avtorlik loyhasi', 'Avtorlik loyhasi'), ('Evroremont', 'Evroremont'), ('O`rta', 'O`rta'), ('Tamir talab', 'Tamir talab'), ('Oddiy suvoq', 'Oddiy suvoq')], max_length=100)),
                ('building_material', models.CharField(choices=[('G`isht', 'G`isht'), ('Monolit', 'Monolit'), ('Panel', 'Panel'), ('Bloklar', 'Bloklar'), ('Boshqa', 'Boshqa')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('description_uz', models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('description_ru', models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ko`chmas mulk',
                'verbose_name_plural': 'Ko`chmas mulklar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HomeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('count_rooms', models.IntegerField(blank=True, choices=[(1, '1 xona'), (2, '2 xona'), (3, '3 xona'), (4, '4 xona'), (5, '5 xona'), (6, '6 va undan ortiq xonalar'), (7, 'Studiya'), (8, 'Ochiq plan')], default=1, null=True)),
                ('from_area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('building_floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repair', models.CharField(blank=True, choices=[('Avtorlik loyhasi', 'Avtorlik loyhasi'), ('Evroremont', 'Evroremont'), ('O`rta', 'O`rta'), ('Tamir talab', 'Tamir talab'), ('Oddiy suvoq', 'Oddiy suvoq')], max_length=100, null=True)),
                ('building_material', models.CharField(blank=True, choices=[('G`isht', 'G`isht'), ('Monolit', 'Monolit'), ('Panel', 'Panel'), ('Bloklar', 'Bloklar'), ('Boshqa', 'Boshqa')], max_length=100, null=True)),
                ('from_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('up_to_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
