# Generated by Django 5.0.1 on 2024-02-26 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homelike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='comforts',
            field=models.ManyToManyField(blank=True, null=True, to='homeapp.comforstypemodel'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homelike',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='homeapp.homemodel'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='home_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.hometypemodel'),
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.homemodel'),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='home_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.hometypemodel'),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.typemodel'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.typemodel'),
        ),
        migrations.AddConstraint(
            model_name='homelike',
            constraint=models.UniqueConstraint(fields=('author', 'home'), name='postLikeUnique'),
        ),
    ]
