# Generated by Django 5.0.1 on 2024-02-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='comforts',
            field=models.ManyToManyField(blank=True, null=True, to='homeapp.comforstypemodel'),
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='home_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.hometypemodel'),
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.typemodel'),
        ),
    ]
